package pe.com.master.machines.model.model

data class ActivePda(
    val codBarraNew: String,
    val codBarraPadreNew: String,
    val componenteCompleto: Int,
    val desActivoNew: String,
    val desAmpliadaNew: String,
    val desCapacidadNew: String,
    val desCentroNew: String,
    val desColorNew: String,
    val desMarcaNew: String,
    val desModeloNew: String,
    val desObservacionNew: String,
    val desPotenciaNew: String,
    val desProcesoNew: String,
    val desTipoActivoNew: String,
    val estado: String,
    val fecha: String,
    val fechaUltModificacion: String,
    val fotoPathLocal: String,
    val fotoPathUrl: String,
    val horometro: Double,
    val idActivosPda: Int,
    val idCentroCosto: Int,
    val idCentroNew: Int,
    val idInventarioActivoFijo: Int,
    val idMarcaNew: Int,
    val idOperario: Int,
    val idPda: String,
    val idProcesoNew: Int,
    val idTipoActivoNew: Int,
    val idTipoBien: Int,
    val idUnidadNew: Int,
    val idUsuarioResponsable: Int,
    val nroChasis: String,
    val nroMotorNew: String,
    val nroPlacaNew: String,
    val nroSerieNew: String,
    val operativo: Int,
    val tag: String
)

