package pe.com.master.machines.model.model

data class ActivePda(
    var codBarraNew: String = "",
    var idActivosPda: Int,
    var idUnidadNew: Int,
    var desActivoNew: String,
    var desAmpliadaNew: String,
    var nroSerieNew: String,
    var nroMotorNew: String,
    var idCentroNew: Int,
    var desCentroNew: String,
    var idProcesoNew: Int,
    var desProcesoNew: String,
    var nroPlacaNew: String,
    var idTipoActivoNew: Int,
    var desTipoActivoNew: String,
    var idMarcaNew: Int,
    var desMarcaNew: String,
    var desModeloNew: String,
    var desPotenciaNew: String,
    var desCapacidadNew: String,
    var idOperario: Int,
    var fecha: String,
    var estado: String,
    var idPda: String,
    var operativo: Int,
    var desObservacionNew: String,
    var fechaUltModificacion: String,
    var codBarraPadreNew: String,
    var tag: String,
    var nroChasis: String,
    var horometro: Double,
    var idUsuarioResponsable: Int,
    var idCentroCosto: Int,
    var componenteCompleto: Int,
    var idTipoBien: Int,
    var fotoPathLocal: String,
    var fotoPathUrl: String,
    var fotoBase64: String,
    var desColorNew: String,
    var idInventarioActivoFijo: Int
)

